import scala.collection.mutable

/** Solves a C Program generated from SVF. Requires a SVFResult which contains meta-information required for matching
 * the result generated by the SVF tool. */

class NaiveSVFSolver(res: SVFResult) extends ExhaustiveSVFSolver(res) {

  val DEBUG = false

  val debugEdges = mutable.Set[(Int, Int)]()
  val debugAddrOf = mutable.Set[(Int, Int)]()
  val debugLoad = mutable.Set[(Int, Int)]()
  val debugStore = mutable.Set[(Int, Int)]()
  val debugGep = mutable.Set[(Int, Int, Int)]()

  /** Since solving GEP instructions require knowing the mapping that SVF chose, this must be provided. */
  override def solve(): CSolution = {
    while (changed) {
      changed = false
      res.program.getInstructions.foreach(i => {
        process(i)
      })

      // Iterate all indirect call sites
      for (indCallSite <- res.indCallsiteMap.keys) {

        // Find actual parameters for call site
        val actualParamList = res.callsiteArgMap(indCallSite)

        // Find the target function pointers...
        val funPtr = res.indCallsiteMap(indCallSite)
        // ... resolve the objVarIds ...
        val funMemIds = sol(funPtr)
        for (funMemId <- funMemIds) {
          // ... retrieve the target function ID
          val funID = res.funMemToFunID(funMemId)
          val formalArgList = res.funArgsMap(funID)

          // Finally propagate from actual to formal
          for (i <- actualParamList.indices) {
            propagate(actualParamList(i), formalArgList(i))
          }

        }
      }
    }

    if DEBUG then
      debugAddrOf.toList.sortBy(e => (e._2, e._1)).foreach(e => {
        if res.nodes.contains(e._2) then
          println(s"${e._2} -- Addr --> ${e._1}")
      })

      debugEdges.toList.sortBy(e => (e._2, e._1)).foreach(e => {
        if res.nodes.contains(e._2) then
          println(s"${e._2} -- Copy --> ${e._1}")
      })

      debugGep.toList.sortBy(e => (e._3, e._1)).foreach(e => {
        if res.nodes.contains(e._3) then
          println(s"${e._3} -- NormalGep (${e._2})--> ${e._1}")
      })

      debugLoad.toList.sortBy(e => (e._2, e._1)).foreach(e => {
        if res.nodes.contains(e._2) then
          println(s"${e._2} -- Load --> ${e._1}")
      })

      debugStore.toList.sortBy(e => (e._2, e._1)).foreach(e => {
        if res.nodes.contains(e._2) then
          println(s"${e._2} -- Store --> ${e._1}")
      })

    sol
  }


  override def propagate(from: Int, to: Int): Unit = {
    if !debugEdges(to, from) && DEBUG && res.nodes(to) then
      debugEdges.add(to, from)
    super.propagate(from, to)
  }

  def process(i: CInstruction): Unit = {
    i match
      case AddrOf(x, y) =>
        addPts(x, y)
        if !debugAddrOf(x, y) && DEBUG && res.nodes(x) then
          debugAddrOf.add(x, y)
      case Copy(x, y) =>
        propagate(y, x)
      case CLoad(x, y) =>
        if !debugLoad(x, y) && DEBUG && res.nodes(x) then
          debugLoad.add(x, y)
        for c <- sol(y) do
          propagate(c, x)
      case CStore(x, y) =>
        if !debugStore(x, y) && DEBUG && res.nodes(x) then
          debugStore.add(x, y)
        for c <- sol(x) do
          propagate(y, c)
      case Gep(dst, base, offset) =>
        if !debugGep(dst, offset, base) && DEBUG && res.nodes(dst) then
          debugGep.add(dst, offset, base)

        // Following the SVF implementation (Andersen.cpp#processGep) - ∀t ⟦base⟧ : gepMap(t, offset) ∈ ⟦dst⟧
        for t <- sol(base) do
          val gepNode = res.gepVarObjMap(t, offset)
          addPts(dst, gepNode)
  }


}
