import scala.collection.mutable

// TODO: Generalize into trait similar to the Java solver

/** Solves a C Program generated from SVF. Requires a SVFResult which contains meta-information required for matching
 * the result generated by the SVF tool. */

class NaiveCExhaustive(SVFResult: SVFResult) {

  val sol = mutable.Map[Cell, mutable.Set[Cell]]().withDefaultValue(mutable.Set.empty)
  var changed = true

  val DEBUG = false

  val debugEdges = mutable.Set[(Cell, Cell)]()
  val debugAddrOf = mutable.Set[(Cell, Cell)]()
  val debugLoad = mutable.Set[(Cell, Cell)]()
  val debugStore = mutable.Set[(Cell, Cell)]()
  val debugGep = mutable.Set[(Cell, Int, Cell)]()

  /** Since solving GEP instructions require knowing the mapping that SVF chose, this must be provided. */
  def solve(): CSolution = {
    while (changed) {
      changed = false
      SVFResult.program.getInstructions.foreach(i => {
        process(i)
      })
    }
    sol
  }

  def addPts(x: Cell, y: Cell): Unit = {
    if !SVFResult.nodes.contains(y) then
      return

    if !sol.contains(x) then
      val fresh = mutable.Set[Cell]()
      sol += x -> fresh

    changed |= sol(x).add(y)
  }

  def propagate(from: Cell, to: Cell): Unit = {
    if !debugEdges(to, from) && DEBUG then
      debugEdges.add(to, from)
      println(s"$from -- Copy --> $to")
    sol(from).foreach(c => addPts(to, c))
  }

  def process(i: CInstruction): Unit = {
    i match
      case AddrOf(x, y) =>
        addPts(x, y)
        if !debugAddrOf(x, y) && DEBUG then
          debugAddrOf.add(x,y)
          println(s"$y -- Addr --> $x")
      case Copy(x, y) =>
        propagate(y, x)
      case CLoad(x, y) =>
        if !debugLoad(x, y) && DEBUG then
          debugLoad.add(x, y)
          println(s"$y -- Load --> $x")
        for c <- sol(y) do
          propagate(c, x)
      case CStore(x, y) =>
        if !debugStore(x, y) && DEBUG then
          debugStore.add(x, y)
          println(s"$y -- Store --> $x")
        for c <- sol(x) do
          propagate(y, c)
      case Gep(dst, base, offset) =>
        if !debugGep(dst, offset, base) && DEBUG then
          debugGep.add(dst, offset, base)
          println(s"$base -- NormalGep($offset) --> $dst")
          
        // Following the SVF implementation (Andersen.cpp#processGep) - ∀t ⟦base⟧ : gepMap(t, offset) ∈ ⟦dst⟧
        for t <- sol(base) do
          t match
            case a: Var =>
              val gepNode = SVFResult.gepVarObjMap(a, offset)
              addPts(dst, gepNode)
            case b: Cell =>
              throw new Error("TODO IF THIS CAN HAPPEN")
  }


}
