import scala.collection.mutable

// TODO: Generalize into trait similar to the Java solver

/** Solves a C Program generated from SVF. Requires a SVFResult which contains meta-information required for matching
 * the result generated by the SVF tool. */

class NaiveCExhaustive(SVFResult: SVFResult) {

  val sol = mutable.Map[Int, mutable.Set[Int]]().withDefaultValue(mutable.Set.empty)
  var changed = true

  val DEBUG = false

  val debugEdges = mutable.Set[(Int, Int)]()
  val debugAddrOf = mutable.Set[(Int, Int)]()
  val debugLoad = mutable.Set[(Int, Int)]()
  val debugStore = mutable.Set[(Int, Int)]()
  val debugGep = mutable.Set[(Int, Int, Int)]()

  /** Since solving GEP instructions require knowing the mapping that SVF chose, this must be provided. */
  def solve(): CSolution = {
    while (changed) {
      changed = false
      SVFResult.program.getInstructions.foreach(i => {
        process(i)
      })

      // Iterate all indirect call sites
      for (indCallSite <- SVFResult.indCallsiteMap.keys) {

        // Find actual parameters for call site
        val actualParamList = SVFResult.callsiteArgMap(indCallSite)

        // Find the target function pointers...
        val funPtr = SVFResult.indCallsiteMap(indCallSite)
        // ... resolve the objVarIds ...
        val funMemIds = sol(funPtr)
        for (funMemId <- funMemIds) {
          // ... retrieve the target function ID
          val funID = SVFResult.funMemToFunID(funMemId)
          val formalArgList = SVFResult.funArgsMap(funID)

          // Finally propagate from actual to formal
          for (i <- actualParamList.indices) {
            propagate(actualParamList(i), formalArgList(i))
          }

        }
      }


      // TODO: After each iteration/worklist order, check all indirect call sites and see if we need to add new 
      //  copy edges from formal to actual parameters
      
    }

   // Addr: OK
   // Copy: Missing 24 --> 45, 27 --> 47, 44 --> 9, 45 --> 21, 46 --> 10, 47 --> 24,
   //   It is NOT in initial, but it IS in final. So it is an edge spawned from a constraint that is missing (for 24 --> 45)

    // 24 --> 45 is missed due to store 24 --> 25 and 25 not containing 45

    if DEBUG then
      debugAddrOf.toList.sortBy(e => (e._2, e._1)).foreach(e => {
        if SVFResult.nodes.contains(e._2) then
          println(s"${e._2} -- Addr --> ${e._1}")
      })

      debugEdges.toList.sortBy(e => (e._2, e._1)).foreach(e => {
        if SVFResult.nodes.contains(e._2) then
          println(s"${e._2} -- Copy --> ${e._1}")
      })

      debugGep.toList.sortBy(e => (e._3, e._1)).foreach(e => {
        if SVFResult.nodes.contains(e._3) then
          println(s"${e._3} -- NormalGep (${e._2})--> ${e._1}")
      })

      debugLoad.toList.sortBy(e => (e._2, e._1)).foreach(e => {
        if SVFResult.nodes.contains(e._2) then
          println(s"${e._2} -- Load --> ${e._1}")
      })

      debugStore.toList.sortBy(e => (e._2, e._1)).foreach(e => {
        if SVFResult.nodes.contains(e._2) then
          println(s"${e._2} -- Store --> ${e._1}")
      })

    sol
  }

  def addPts(x: Int, y: Int): Unit = {
    if !SVFResult.nodes.contains(x) then
      return

    if !sol.contains(x) then
      val fresh = mutable.Set[Int]()
      sol += x -> fresh

    changed |= sol(x).add(y)
  }

  private def propagate(from: Int, to: Int): Unit = {
    if !debugEdges(to, from) && DEBUG && SVFResult.nodes(to) then
      debugEdges.add(to, from)
    sol(from).foreach(c => addPts(to, c))
  }

  def process(i: CInstruction): Unit = {
    i match
      case AddrOf(x, y) =>
        addPts(x, y)
        if !debugAddrOf(x, y) && DEBUG && SVFResult.nodes(x) then
          debugAddrOf.add(x, y)
      case Copy(x, y) =>
        propagate(y, x)
      case CLoad(x, y) =>
        if !debugLoad(x, y) && DEBUG && SVFResult.nodes(x) then
          debugLoad.add(x, y)
        for c <- sol(y) do
          propagate(c, x)
      case CStore(x, y) =>
        if !debugStore(x, y) && DEBUG && SVFResult.nodes(x) then
          debugStore.add(x, y)
        for c <- sol(x) do
          propagate(y, c)
      case Gep(dst, base, offset) =>
        if !debugGep(dst, offset, base) && DEBUG && SVFResult.nodes(dst) then
          debugGep.add(dst, offset, base)

        // Following the SVF implementation (Andersen.cpp#processGep) - ∀t ⟦base⟧ : gepMap(t, offset) ∈ ⟦dst⟧
        for t <- sol(base) do
          val gepNode = SVFResult.gepVarObjMap(t, offset)
          addPts(dst, gepNode)
  }


}
